### ISSUE TITLE
so this is not robust lock?

### ISSUE THREAD

**Issue by iperov** [drandreaskrueger/lockbydir#1]
> Very improbable, but not impossible.  Then two could both be locking.

**Comment by drandreaskrueger** [comment]
for full context, see the comments [here](https://github.com/drandreaskrueger/lockbydir/blob/8d050358b84ef9d3b2e72a1b6dd751bf09cec965/lockbydir.py#L46-L61), incl this:

> @todo: Possible future improvement:  
> TODO 1:  [...]
> I have no idea how to solve this. What is the equivalent of a successful mkdir, 
when successful non-existence of a directory is the criterion? While at the same 
time exactly that is the starting point for the opposite process. A riddle. 

Plus forgive me (and my code back then), because I was much more of a noob still, 8 years ago. Plus, I have never again needed that lock, so I am also not gonna pretend that I have had newer ideas about it. 

What about you?
